name: Fox
version: '0.1'

main: dev.isnow.foxac.FoxAC
load: POSTWORLD

authors:
  - "5170"
  - "Lindgey"

commands:
  fox:
    description: Commands for Fox Anticheat.
    usage: /fox
    aliases: [foxac, fac, foxanticheat]

softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - Geyser-Spigot